#!/bin/sh -ex

out/DebugHost/primordialsoup out/snapshots/HelloApp.vfuel
out/ReleaseHost/primordialsoup out/snapshots/HelloApp.vfuel

out/DebugHost/primordialsoup out/snapshots/TestRunner.vfuel
out/ReleaseHost/primordialsoup out/snapshots/TestRunner.vfuel

out/ReleaseHost/primordialsoup out/snapshots/BenchmarkRunner.vfuel
