#!/bin/sh -e

test_x64() {
  set -x
  out/DebugX64/primordialsoup out/snapshots/HelloApp.vfuel
  out/ReleaseX64/primordialsoup out/snapshots/HelloApp.vfuel

  out/DebugX64/primordialsoup out/snapshots/TestRunner.vfuel
  out/ReleaseX64/primordialsoup out/snapshots/TestRunner.vfuel

  out/ReleaseX64/primordialsoup out/snapshots/BenchmarkRunner.vfuel
}

test_x64_and_ia32() {
  set -x
  out/DebugIA32/primordialsoup out/snapshots/HelloApp.vfuel
  out/DebugX64/primordialsoup out/snapshots/HelloApp.vfuel
  out/ReleaseIA32/primordialsoup out/snapshots/HelloApp.vfuel
  out/ReleaseX64/primordialsoup out/snapshots/HelloApp.vfuel

  out/DebugIA32/primordialsoup out/snapshots/TestRunner.vfuel
  out/DebugX64/primordialsoup out/snapshots/TestRunner.vfuel
  out/ReleaseIA32/primordialsoup out/snapshots/TestRunner.vfuel
  out/ReleaseX64/primordialsoup out/snapshots/TestRunner.vfuel

  out/ReleaseIA32/primordialsoup out/snapshots/BenchmarkRunner.vfuel
  out/ReleaseX64/primordialsoup out/snapshots/BenchmarkRunner.vfuel
}

test_arm64() {
  set -x
  out/DebugARM64/primordialsoup out/snapshots/HelloApp.vfuel
  out/ReleaseARM64/primordialsoup out/snapshots/HelloApp.vfuel

  out/DebugARM64/primordialsoup out/snapshots/TestRunner.vfuel
  out/ReleaseARM64/primordialsoup out/snapshots/TestRunner.vfuel

  out/ReleaseARM64/primordialsoup out/snapshots/BenchmarkRunner.vfuel
}

test_arm() {
  set -x
  out/DebugARM/primordialsoup out/snapshots/HelloApp.vfuel
  out/ReleaseARM/primordialsoup out/snapshots/HelloApp.vfuel

  out/DebugARM/primordialsoup out/snapshots/TestRunner.vfuel
  out/ReleaseARM/primordialsoup out/snapshots/TestRunner.vfuel

  out/ReleaseARM/primordialsoup out/snapshots/BenchmarkRunner.vfuel
}

test_mips() {
  set -x
  out/DebugMIPS/primordialsoup out/snapshots/HelloApp.vfuel
  out/ReleaseMIPS/primordialsoup out/snapshots/HelloApp.vfuel

  out/DebugMIPS/primordialsoup out/snapshots/TestRunner.vfuel
  out/ReleaseMIPS/primordialsoup out/snapshots/TestRunner.vfuel

  out/ReleaseMIPS/primordialsoup out/snapshots/BenchmarkRunner.vfuel
}

case $(uname -m) in
  x86_64)
    case $(uname -s) in
      Darwin) test_x64 ;;
      *) test_x64_and_ia32
    esac ;;
  aarch64) test_arm64 ;;
  armv7l) test_arm ;;
  armv6l) test_arm ;;
  mips) test_mips ;;
  *) echo Unknown architecture $(uname -m)
esac
